//
//  HomeRouter.swift
//  TheMovieDb
//
//  Created by Marcio Habigzang Brufatto on 16/10/19.
//  Copyright (c) 2019 Marcio Habigzang Brufatto. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol HomeRoutingLogic {
    func routerToMovies()
}

protocol HomeDataPassing {
    var dataStore: HomeDataStore? { get }
}

class HomeRouter: NSObject, HomeRoutingLogic, HomeDataPassing {
    weak var viewController: HomeViewController?
    var dataStore: HomeDataStore?
    
    // MARK: Routing
    func routerToMovies() {
        let destinationVC = MoviesViewController()
        var destinationDS = destinationVC.router?.dataStore
        passDataToMovie(source: dataStore!, destination: &destinationDS!)
        navigateToMovie(source: viewController!, destination: destinationVC )
    }
    
    func passDataToMovie(source: HomeDataStore, destination: inout MoviesDataStore) {
        destination.movies = source.movies
    }
    
    func navigateToMovie(source: HomeViewController, destination: MoviesViewController) {
        source.show(destination, sender: nil)
    }
}
