//
//  HomeInteractor.swift
//  TheMovieDb
//
//  Created by Marcio Habigzang Brufatto on 16/10/19.
//  Copyright (c) 2019 Marcio Habigzang Brufatto. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomeBusinessLogic {
    func doRequestMovies(request: HomeScene.Load.Request)
}

protocol HomeDataStore {
    var movies: [Movie]? { get set }
    var totalPages: Int? { get set }
    var totalResults: Int? { get set }
}

class HomeInteractor: HomeBusinessLogic, HomeDataStore {
    var presenter: HomePresentationLogic?
    var worker: HomeWorker?
    var movies: [Movie]?
    var totalPages: Int?
    var totalResults: Int?
    
    // MARK: Do something
    
    func doRequestMovies(request: HomeScene.Load.Request) {
        worker = HomeWorker()
        worker?.doRequestMovies(completion: { movieBase in
            self.movies = movieBase.movies
            self.totalPages = movieBase.totalPages
            self.totalResults = movieBase.totalResults
            let response = HomeScene.Load.Response(totalPages: movieBase.totalPages, totalResults: movieBase.totalResults, movies: movieBase.movies)
            self.presenter?.presentInitialMovies(response: response)
        })
    }
}
