//
//  HomePresenter.swift
//  TheMovieDb
//
//  Created by Marcio Habigzang Brufatto on 16/10/19.
//  Copyright (c) 2019 Marcio Habigzang Brufatto. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomePresentationLogic {
    func presentInitialMovies(response: HomeScene.Load.Response)
}

class HomePresenter: HomePresentationLogic {
    weak var viewController: HomeDisplayLogic?
    
    // MARK: Do something
    
    func presentInitialMovies(response: HomeScene.Load.Response) {
        let viewModel = HomeScene.Load.ViewModel(movies: response.movies)
        viewController?.displayInitialMovies(viewModel: viewModel)
    }
}
