//
//  MoviesInteractor.swift
//  TheMovieDb
//
//  Created by Marcio Habigzang Brufatto on 16/10/19.
//  Copyright (c) 2019 Marcio Habigzang Brufatto. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MoviesBusinessLogic {
    func doLoadMovies(request: MoviesScene.Load.Request)
}

protocol MoviesDataStore {
    var movies: [Movie]? { get set }
}

class MoviesInteractor: MoviesBusinessLogic, MoviesDataStore {
    var presenter: MoviesPresentationLogic?
    var worker: MoviesWorker?
    var movies: [Movie]?
    
    func doLoadMovies(request: MoviesScene.Load.Request) {
        let response = MoviesScene.Load.Response(movies: movies!)
        presenter?.presentMovies(response: response)
    }
    
    
}
