//
//  MoviesModels.swift
//  TheMovieDb
//
//  Created by Marcio Habigzang Brufatto on 16/10/19.
//  Copyright (c) 2019 Marcio Habigzang Brufatto. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum MoviesScene {
    // MARK: Use cases
    
    enum Load {
        struct Request {
            let currentPage: Int
        }
        struct Response {
            let totalPages: Int
            let totalResults: Int
            let movies: [Movie]
        }
        struct ViewModel {
            let totalPages: Int
            let totalResults: Int
            let movies: [Movie]
        }
    }
    
    enum MoviesToMovie {
        struct Request {
            let movie: Movie
        }
        struct Response {
            let movie: Movie
        }
        struct ViewModel {
            let movie: Movie
        }
    }
    
    enum LoadMovieByName {
        struct Request {
            let title: String
        }
    }
}
