//
//  MoviesPresenter.swift
//  TheMovieDb
//
//  Created by Marcio Habigzang Brufatto on 16/10/19.
//  Copyright (c) 2019 Marcio Habigzang Brufatto. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MoviesPresentationLogic {
    func presentMovies(response: MoviesScene.Load.Response)
    func presentMovieDetail(response: MoviesScene.MoviesToMovie.Response)
}

class MoviesPresenter: MoviesPresentationLogic {
    weak var viewController: MoviesDisplayLogic?
    
    // MARK: Do something
    
    func presentMovies(response: MoviesScene.Load.Response) {
        let viewModel = MoviesScene.Load.ViewModel(totalPages: response.totalPages, totalResults: response.totalResults ,movies: response.movies)
        viewController?.displayMovies(viewModel: viewModel)
    }
    
    func presentMovieDetail(response: MoviesScene.MoviesToMovie.Response) {
        let viewModel = MoviesScene.MoviesToMovie.ViewModel(movie: response.movie)
        viewController?.displayToMovieDetail(viewModel: viewModel)
    }
}
