//
//  MoviesWorker.swift
//  TheMovieDb
//
//  Created by Marcio Habigzang Brufatto on 16/10/19.
//  Copyright (c) 2019 Marcio Habigzang Brufatto. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class MoviesWorker {
    func doRequestMovies(page: Int = 1, completion: @escaping(MovieBase) -> Void) {
        NetworkManager.shared.fetchMovies(page: page) { movies in
            completion(movies)
        }
    }
}
