//
//  MoviesRouter.swift
//  TheMovieDb
//
//  Created by Marcio Habigzang Brufatto on 16/10/19.
//  Copyright (c) 2019 Marcio Habigzang Brufatto. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol MoviesRoutingLogic {
    func routerToMovieDetail()
}

protocol MoviesDataPassing {
    var dataStore: MoviesDataStore? { get }
}

class MoviesRouter: NSObject, MoviesRoutingLogic, MoviesDataPassing {
    weak var viewController: MoviesViewController?
    var dataStore: MoviesDataStore?
    
    // MARK: Routing
    func routerToMovieDetail() {
        let destinationVC = MovieDetailViewController()
        var destinationDS = destinationVC.router?.dataStore
        passDataToMovieDetail(source: dataStore!, destination: &destinationDS!)
        navigateToMovieDetail(source: viewController!, destination: destinationVC )
    }
    
    func passDataToMovieDetail(source: MoviesDataStore, destination: inout MovieDetailDataStore) {
        destination.movie = source.movie
    }
    
    func navigateToMovieDetail(source: MoviesViewController, destination: MovieDetailViewController) {
        source.show(destination, sender: nil)
    }
}
