//
//  MovieDetailWorker.swift
//  TheMovieDb
//
//  Created by Marcio Habigzang Brufatto on 17/10/19.
//  Copyright (c) 2019 Marcio Habigzang Brufatto. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class MovieDetailWorker {
    func doLoadMovie(movieId: Int, completion: @escaping(Movie) -> Void) {
        NetworkManager.shared.fetchMovie(movieId: movieId) { movie in
            completion(movie)
        }
    }
}
