//
//  MovieDetailPresenter.swift
//  TheMovieDb
//
//  Created by Marcio Habigzang Brufatto on 17/10/19.
//  Copyright (c) 2019 Marcio Habigzang Brufatto. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MovieDetailPresentationLogic {
    func presentMovie(response: MovieDetail.Load.Response)
}

class MovieDetailPresenter: MovieDetailPresentationLogic {
    weak var viewController: MovieDetailDisplayLogic?
    
    // MARK: Do something
    
    func presentMovie(response: MovieDetail.Load.Response) {
        let viewModel = MovieDetail.Load.ViewModel(movie: response.movie)
        viewController?.displayMovie(viewModel: viewModel)
    }
}
