//
//  MovieDetailModels.swift
//  TheMovieDb
//
//  Created by Marcio Habigzang Brufatto on 17/10/19.
//  Copyright (c) 2019 Marcio Habigzang Brufatto. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum MovieDetail {
    // MARK: Use cases
    
    enum Load {
        struct Request {
        }
        struct Response {
            let movie: Movie
        }
        struct ViewModel {
            let movie: Movie
        }
    }
}
