//
//  MovieDetailInteractor.swift
//  TheMovieDb
//
//  Created by Marcio Habigzang Brufatto on 17/10/19.
//  Copyright (c) 2019 Marcio Habigzang Brufatto. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MovieDetailBusinessLogic {
    func doLoadMovie(request: MovieDetail.Load.Request)
}

protocol MovieDetailDataStore {
    var movie: Movie? { get set }
}

class MovieDetailInteractor: MovieDetailBusinessLogic, MovieDetailDataStore {
    var presenter: MovieDetailPresentationLogic?
    var worker: MovieDetailWorker?
    var movie: Movie?
    
    func doLoadMovie(request: MovieDetail.Load.Request) {
        worker = MovieDetailWorker()
        worker?.doLoadMovie(movieId: movie!.id) { movie in
            let response = MovieDetail.Load.Response(movie: movie)
            self.presenter?.presentMovie(response: response)
        }
    }
}
